[package]
name = "process_viewer"
version = "0.4.0"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

description = "A process viewer GUI"
repository = "https://github.com/GuillaumeGomez/process-viewer"
license = "MIT"
homepage = "https://github.com/GuillaumeGomez/process-viewer"

readme = "README.md"

keywords = ["GUI", "process", "viewer", "gtk"]

[dependencies]
cairo-rs = "0.8"
gdk = "0.12"
gdk-pixbuf = "0.8"
gio = "0.8"
glib = "0.9"
gtk = "0.8"
pango = "0.8"
sysinfo = "0.14"
libc = "0.2"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"

[[bin]]
name = "process_viewer"
path = "src/process_viewer.rs"
