[package]
name = "process_viewer"
version = "0.0.7"
authors = ["Guillaume Gomez <guillaume1.gomez@gmail.com>"]

description = "A process viewer GUI"
repository = "https://github.com/GuillaumeGomez/process-viewer"
license = "MIT"
homepage = "https://github.com/GuillaumeGomez/process-viewer"

readme = "README.md"

keywords = ["GUI", "process", "viewer", "gtk"]

[dependencies]
gtk-sys = "0.3.1"
pango-sys = "0.3.1"
gtk = "0.1.0"
glib = "0.1.0"
cairo-rs = "0.1.0"
gdk = "0.5.0"
libc = "0.2"
sysinfo = "0.3"

[[bin]]
name = "process_viewer"
